"""add_role_to_resource_allocations

Revision ID: 021c9bd12bc7
Revises: 342fb29e6e6d
Create Date: 2025-02-17 09:56:54.309053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '021c9bd12bc7'
down_revision: Union[str, None] = '342fb29e6e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'billing_type',
               existing_type=postgresql.ENUM('TIME_AND_MATERIALS', 'FIXED_PRICE', name='billingtype'),
               nullable=False)
    op.add_column('resource_allocations', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_allocations', 'role')
    op.alter_column('projects', 'billing_type',
               existing_type=postgresql.ENUM('TIME_AND_MATERIALS', 'FIXED_PRICE', name='billingtype'),
               nullable=True)
    # ### end Alembic commands ###
