"""add_project_billing_rates

Revision ID: 4a963529e876
Revises: 5b070d0659e0
Create Date: 2025-02-19 23:57:53.675523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a963529e876'
down_revision: Union[str, None] = '5b070d0659e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_billing_rates',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('billing_rate_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), 
             server_default=sa.text('CURRENT_TIMESTAMP'),
             nullable=False),
    sa.Column('active', sa.Boolean(), 
             server_default='true',
             nullable=False),
    sa.ForeignKeyConstraint(
        ['project_id'], ['projects.id'],
        ondelete='CASCADE'
    ),
    sa.ForeignKeyConstraint(
        ['billing_rate_id'], ['billing_rates.id'],
        ondelete='CASCADE'
    ),
    sa.PrimaryKeyConstraint('project_id', 'billing_rate_id')
    )
    
    # Aggiungi indici per migliorare le performance
    op.create_index(
        'ix_project_billing_rates_project_id',
        'project_billing_rates',
        ['project_id']
    )
    op.create_index(
        'ix_project_billing_rates_billing_rate_id',
        'project_billing_rates',
        ['billing_rate_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Prima verifica se gli indici esistono
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indices = inspector.get_indexes('project_billing_rates')
    
    # Rimuovi gli indici se esistono
    existing_indices = [idx['name'] for idx in indices]
    
    if 'ix_project_billing_rates_billing_rate_id' in existing_indices:
        op.drop_index('ix_project_billing_rates_billing_rate_id',
                     table_name='project_billing_rates')
    
    if 'ix_project_billing_rates_project_id' in existing_indices:
        op.drop_index('ix_project_billing_rates_project_id',
                     table_name='project_billing_rates')
    
    # Infine rimuovi la tabella
    op.drop_table('project_billing_rates')
