"""fix_project_user_relationships

Revision ID: 5b070d0659e0
Revises: 5220168451a2
Create Date: 2025-02-19 23:55:27.186420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b070d0659e0'
down_revision: Union[str, None] = '5220168451a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_users', 'consultant_roles', ['role_id'], ['id'])
    op.add_column('resource_allocations', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource_allocations', 'consultant_roles', ['role_id'], ['id'])
    op.drop_column('resource_allocations', 'end_date')
    op.drop_column('resource_allocations', 'start_date')
    op.drop_column('resource_allocations', 'allocation_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_allocations', sa.Column('allocation_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('resource_allocations', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('resource_allocations', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resource_allocations', type_='foreignkey')
    op.drop_column('resource_allocations', 'role_id')
    op.drop_constraint(None, 'project_users', type_='foreignkey')
    op.drop_column('project_users', 'role_id')
    # ### end Alembic commands ###
