"""fix_consultant_role_relationships

Revision ID: 9ae100df771a
Revises: 7b1c762d58a8
Create Date: 2025-02-19 23:50:32.873840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae100df771a'
down_revision: Union[str, None] = '7b1c762d58a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_project_users_role', 'project_users', type_='foreignkey')
    op.drop_column('project_users', 'role')
    op.add_column('resource_allocations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('fk_resource_allocations_role', 'resource_allocations', type_='foreignkey')
    op.drop_column('resource_allocations', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_allocations', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_resource_allocations_role', 'resource_allocations', 'consultant_roles', ['role'], ['id'])
    op.drop_column('resource_allocations', 'created_at')
    op.add_column('project_users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_project_users_role', 'project_users', 'consultant_roles', ['role'], ['id'])
    op.drop_column('project_users', 'id')
    # ### end Alembic commands ###
